[package]
name = "ob3"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
rayon = "1.11"
thiserror = "2.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
